### ISSUE TITLE
Nominating Cristian Kiss as contributor

### ISSUE THREAD

**Issue by floridemai** [covidgreen/organization#2]
@covidgreen/members 
Cristian Kiss ([ckiss](https://github.com/ckiss)) was involved in releasing the covid tracker for Northern Ireland. I think he'll help us improving this moving forward, so I'm nominating him as as @covidgreen/members for commit access

Please 👍🏻 or 👎🏻 on the nomination.

**Comment by jasnell** [comment]
If there are no objections on this by end of the day tomorrow I'll consider it approved!
