### ISSUE TITLE
Nominating Patrick Hindmarsh for commit access and Covid Green TSC

### ISSUE THREAD

**Issue by jasnell** [covidgreen/organization#4]
I'd like to nominate Patrick Hindmarsh (@phindmarsh) from the New Zealand Health Ministry for commit access and for the covid green TSC ... /cc @colmharte @aspiringarc

New Zealand is leveraging components of covid green in their application.

**Comment by aspiringarc** [comment]
I'm happy to support Patricks nomination

**Comment by colmharte** [comment]
LGTM

**Comment by jasnell** [comment]
Org invite sent!
