### ISSUE TITLE
Nominating Geoffrey Ballenden for commit access and TSC

### ISSUE THREAD

**Issue by jasnell** [covidgreen/organization#5]
I'd like to nominate Geoffrey Ballenden  (@GeoffNZ) from the Rush for commit access and for the covid green TSC ... /cc @colmharte @aspiringarc

Rush is using parts of covid green in the New Zealand app and elsewhere.

**Comment by aspiringarc** [comment]
I'm happy to support Geoffrey's nomination

**Comment by colmharte** [comment]
LGTM

**Comment by jasnell** [comment]
Org invite sent!
